/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gogameclient;

import java.awt.Font;
import java.io.File;

/**
 *
 * @author abdel
 */
public class EndScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EndScreen.class.getName());

    /**
     * Creates new form StartScreen
     */
    public EndScreen() {
        initComponents();
        try{
            File fontStyle = new File ("src/main/resources/fonts/Retro-Gaming.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(44f);
            jLabel_Winner.setFont(font);
        } catch(Exception e){
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 80), new java.awt.Dimension(300, 80), new java.awt.Dimension(80, 80));
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Winner = new javax.swing.JLabel();
        jButton_Exit = new javax.swing.JButton();
        jButton_PlayAgain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Title1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 80), new java.awt.Dimension(300, 80), new java.awt.Dimension(80, 80));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GO Game");
        setBackground(new java.awt.Color(249, 249, 249));
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));
        MainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        MainPanel.setLayout(new javax.swing.BoxLayout(MainPanel, javax.swing.BoxLayout.LINE_AXIS));
        MainPanel.add(filler1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(337, 256));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Winner.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_Winner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Winner.setText("BLACK");
        jPanel1.add(jLabel_Winner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        jButton_Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Exit.setText("EXIT");
        jButton_Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, 50));

        jButton_PlayAgain.setBackground(new java.awt.Color(102, 51, 0));
        jButton_PlayAgain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_PlayAgain.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PlayAgain.setText("PLAY AGAIN");
        jButton_PlayAgain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_PlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlayAgainActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_PlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MATCH CONCLUDED");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jLabel_Title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel_Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title1.setText("WINNER :");
        jPanel1.add(jLabel_Title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        MainPanel.add(jPanel2);
        MainPanel.add(filler2);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlayAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PlayAgainActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EndScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_PlayAgain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Title1;
    private javax.swing.JLabel jLabel_Winner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
